## Create a n-D matrix will all Zeroes

In [109]:
def zeroes_matrix(shape, matrix=0): 
    while(shape!=[]):
        matrix = [matrix for j in range(shape[-1])]
        shape= shape[:-1]
    return matrix

In [136]:
zeroes_matrix([1,2,1,2])

[[[[0, 0]], [[0, 0]]]]

## Get shape of a matrix 

In [113]:
def get_shape(A):
    shape = []
    while (type(a)==type([])):
        shape.append(len(A))
        A = A[0]
    return shape

In [114]:
A = [[[[0, 0]], [[0, 0]]]]
print(get_shape(A))

[1, 2, 1, 2]


## Create a copy of a n-d matrix

In [141]:
a = [1,2,3]
b = a
c = a[:]
a [0] = 100

[3, 2, 1]


In [87]:
def copy_matrix(matrix):
    shape = get_shape(matrix)
    copy = []
    if len(shape) == 1: ## matrix is 1d i.e. row
        for ele in matrix:
            copy.append(ele)
        return copy
    else:
        for ele in matrix:
            res = copy_matrix(ele)
            copy.append(res)
    return copy        

In [97]:
A = [[[[[1, 2], [3, 4]], [[1, 2], [3, 11]]]]]
result = copy_matrix(A)
print(result)
A[0][0][0][0][0] = 100
print(A)
print(result)

[[[[[1, 2], [3, 4]], [[1, 2], [3, 11]]]]]
[[[[[100, 2], [3, 4]], [[1, 2], [3, 11]]]]]
[[[[[1, 2], [3, 4]], [[1, 2], [3, 11]]]]]


## Print a matrix

In [146]:
def print_matrix(matrix):
    for i, row in enumerate(matrix):
        if i==0:
            print('[', end='')
        if i > 0:
            print(' ', end='')
        print(row, end='')
        if i<len(matrix)-1:
            print(',')
        if i==len(matrix)-1:
            print(']')

In [147]:
matrix = [[1, 2], [3, 4], [5, 6], [7, 8]]
print_matrix(matrix)

[[1, 2],
 [3, 4],
 [5, 6],
 [7, 8]]


In [148]:
matrix = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print_matrix(matrix)

[[[1, 2], [3, 4]],
 [[5, 6], [7, 8]]]


## Add two matrix

In [225]:
def add_A_B(A, B):
    row_a, col_a = get_shape(A)
    row_b, col_b = get_shape(B)
    
    if (row_a != row_b or  col_a != col_b):
        raise Exception('Rows*Columns does not match')
        
    addition=[]
    for i in range(len(A)):
        addition.append([A[i][j]+B[i][j] for j in range(len(A[i]))])
    return addition

In [226]:
A = [[1, 3], [5, 7]]
B = [[8, 2], [4, 6]]
ans = add_A_B(A, B)
print (ans)

[[9, 5], [9, 13]]


## Dot product 

In [79]:
def dot_product(A, B):
    row_a, col_a = get_shape(A)
    row_b, col_b = get_shape(B)
    
    if (row_a != row_b or  col_a != col_b):
        raise Exception('Rows*Columns does not match')

    dot_prod = 0    
    for i in range(len(A)):
        for j in range(len(A[0])):
            dot += A[i][j]*B[i][j]
    return dot

In [80]:
A = [[1, 4, 3], [2, 1, 5]]
B = [[1, 4, 3], [2, 1, 5]]
ans = dot_product(A, B)
print(ans)

56


## Matrix product

In [121]:
import numpy as np

In [122]:
def matrix_product(A, B):
    row_a, col_a = get_shape(A)
    row_b, col_b = get_shape(B)
    
    if (col_a != row_b):
        raise Exception('Number of rows in matrix A does not match number of columns in matrix B')
        
    matrix_prod = np.zeros((row_a, col_b))
    
    for i in range(len(A)):
        for j in range(len(B[0])): 
            for k in range(len(B)):
                matrix_prod[i][j] += A[i][k]*B[k][j]
    return matrix_prod

In [123]:
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
  
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]

matrix_prod = matrix_product(A, B)
print_matrix(matrix_prod)

[[114. 160.  60.  27.],
[74. 97. 73. 14.],
[119. 157. 112.  23.]]


## Transposition

In [126]:
def transpose_matrix(matrix):
    num_rows, num_cols = get_shape(matrix)

    transpose = []
    for i in range(len(matrix[0])): # num col
        val = [matrix[j][i] for j in range(len(matrix))] # num rows
        transpose.append(val)
               
    return transpose

In [128]:
A = [[1, 4, 3], [2, 1, 5]]
res = transpose_matrix(A)
print_matrix(res)

[[1, 2],
[4, 1],
[3, 5]]


In [131]:
def flatten(matrix):
    num_rows, num_cols = get_shape(matrix)
    flatten = []
    for i in range(num_rows):
        flatten+=matrix[i]
    return flatten

In [133]:
A = M = [[6, 4], [4, 8], [3, 5]]
res = flatten(A)
print(res)

[6, 4, 4, 8, 3, 5]


## Matrix concatenation

In [ ]:
def concatenate(A, B, type_):
    row_a, col_a = get_shape(A)
    row_b, col_b = get_shape(B)
    
    concat_matrix = []
    if type_.lower()=='Horizontal':
        if (row_a!=row_b):
            raise Exception('Number of rows in matrix A does not match number of rows in matrix B')
        
        for row in row_a:
            concat_matrix.append(A[row]+B[row])
    else:
        A_T = transpose_matrix(A)
        B_T = transpose_matrix(B)
    

In [ ]:
# 16.3